### ISSUE TITLE
Public layer?

### ISSUE THREAD

**Issue by mwarkentin** [aws-samples/aws-lambda-layer-awscli#1]
Not sure what’s involved, but I’m wondering if it’d be possible to publish a public version of this layer that could be used directly?

**Comment by pahud** [comment]
Hi, we don't provide public layer at this moment. However, it's very simple to build your own layer from scratch by simply

```
$ make build layer-zip layer-upload layer-publish
```

https://github.com/aws-samples/aws-lambda-layer-awscli#option-2-create-layer-from-scratch
