### ISSUE TITLE
Does this layer support Python3.8 runtime?

### ISSUE THREAD

**Issue by Sushant20** [aws-samples/aws-lambda-layer-awscli#10]
Getting '/opt/awscli/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory' during execution of aws cli command
Looks like I have to use lambda- python 3.8 docker image to build the layer, am i missing something?
@pahud

**Comment by pahud** [comment]
Not yet. But I will try build AWS CLI v2 with python3 support as a layer. Can you tell me your scenario why you need awscli layer for python3.8 runtime?

**Comment by Sushant20** [comment]
@pahud Thanks for prompt reply, all my functions are running on python3.8 and i need aws cli(sync command) . Do you have a workaround for this scenario, let me know if I am missing anything

**Comment by pahud** [comment]
I just created a new `awscli-v2-python37` branch for this with `awscliv2` and `python3` support.
https://github.com/aws-samples/aws-lambda-layer-awscli/tree/awscli-v2-python37

And the `Dockerfile` seems working now
https://github.com/aws-samples/aws-lambda-layer-awscli/blob/awscli-v2-python37/Dockerfile

you may build your layer from your local environment and publish it like this

```sh
# edit the Makefile first
$ make layer-build sam-layer-package sam-layer-deploy
```

When your layer is published, you can create a lambda function with python3.8 runtime like this

https://github.com/aws-samples/aws-lambda-layer-awscli/blob/awscli-v2-python37/samples/python3-runtime/aws_version.py

And you should be able to see the AWS CLI response

<img width="1633" alt="圖片" src="https://user-images.githubusercontent.com/278432/79758602-2e8f7f80-8350-11ea-8421-8a3ecf1f373f.png">

I have yet to test it with `aws s3 sync` but it should work in both `python3.7` and `python3.8` runtime.

Let me know if it works in your environment.

**Comment by Sushant20** [comment]
@pahud Thanks for quick turnaround, I did build of Dockerfile and deployed it on Lambda for sync command testing and it works fine however it seems to take around 12 secs to execute 'aws cli version' output (128 MB allocated to Lambda). This seems to take more time than awscli v1, I have created using https://bezdelev.com/hacking/aws-cli-inside-lambda-layer-aws-s3-sync/ in the past. Do you see similar behaviour?

**Comment by pahud** [comment]
@Sushant20 

Yes you are right. I just noticed the default 128MB memory will just timeout after the default 3 seconds. I have no chance to investigate the root cause but raising the memory to 512MB does help. In my case above, the `aws --version` with 512MB takes 2719ms while the immediate succeeding invocations take around 2000ms and nodejs12 runtime has similar duration with this layer as well. I hope you find it useful and I am planing to create a `v2` branch for separate development.

**Comment by bdelage** [comment]
Hi 
Just stopping by to say I'm very interested in this layer as well, as I want to use the aws cli credential helper for CodeCommit to be able to perform tasks with a python 3.8 runtime Lambda function.
Cheers

**Comment by pahud** [comment]
@bdelage Happy to hear that. Please don't hesitate to let me know if the new `awscli-v2-python37` branch works well in your python3.8 environment. 

Cheers!

**Comment by Falydoor** [comment]
Hey,

Just writing a small message to say thanks because this is a pretty cool layer and I like the easy integration with CDK.

Good stuff!
