### ISSUE TITLE
Does this work with Ruby runtimes?

### ISSUE THREAD

**Issue by trackedsupport** [aws-samples/aws-lambda-layer-awscli#12]
Forgive my ignorance. I’m trying to figure how to add aws s3 cli as a layer to my ruby function. Im not exactly sure how to package and deploy these things so I wanted to make sure - does this work with Ruby 2.5 or Ruby 2.7 runtime?

**Comment by pahud** [comment]
> Forgive my ignorance. I’m trying to figure how to add aws s3 cli as a layer to my ruby function. Im not exactly sure how to package and deploy these things so I wanted to make sure - does this work with Ruby 2.5 or Ruby 2.7 runtime?

This layer is designed for custom runtime, but it's also possible for other runtimes as long as you can execute the `/opt/awscli/aws` from the runtime environment.

When you attach this layer to the runtime, `/opt/awscli` will be mounted to your runtime environment and you can execute any executable under `/opt/awscli`.

However, as we didn't test the Ruby runtimes and it's primarily designed for custom runtime only. You will need to build your own layer and test it.

**Comment by trackedsupport** [comment]
Thanks for the info. I got it to build and installed as a layer. I then was able to call it with `/opt/awscli/aws` but I get the following error. 

`/opt/awscli/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory`

**Comment by trackedsupport** [comment]
I was able to get it to work with your awscli-v2-python37 branch with both python and ruby runtimes! 

One weird thing is that the ffmpeg in the python runtime is almost twice as fast as the ruby runtime and they are using the same FFMPEG layer! So weird!
