### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by eshankt** [aws-samples/aws-lambda-layer-awscli#17]
I am getting a permission denied error
![image](https://user-images.githubusercontent.com/65946441/97278399-c1f5c000-185f-11eb-8fb2-8dd29ad93e44.png)

**Comment by sanjeev1994tiwari** [comment]
i am getting permission issue

Response:
{
  "errorType": "Error",
  "errorMessage": "Command failed: /opt/awscli/aws --version\n/bin/sh: /opt/awscli/aws: Permission denied\n",
  "trace": [
    "Error: Command failed: /opt/awscli/aws --version",
    "/bin/sh: /opt/awscli/aws: Permission denied",
    "",
    "    at checkExecSyncError (child_process.js:635:11)",
    "    at execSync (child_process.js:671:15)",
    "    at internal/util.js:297:30",
    "    at new Promise (<anonymous>)",
    "    at execSync (internal/util.js:296:12)",
    "    at Runtime.exports.handler (/var/task/index.js:47:12)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
