### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by jansony1** [aws-samples/aws-lambda-layer-awscli#3]
Hi pahud.

This `	cp Makefile.lambda ./lambda-bundle/Makefile; 
`  in below section of Makefile command should be `cp Makefile ./lambda-bundle/Makefile;`
```
func-zip:
	rm -rf ./lambda-bundle; mkdir ./lambda-bundle
	chmod +x main.sh
	cp main.sh bootstrap ./lambda-bundle;
	cp Makefile.lambda ./lambda-bundle/Makefile;
```

**Comment by pahud** [comment]
thank you @jansony1 

https://github.com/aws-samples/aws-lambda-layer-awscli/commit/846aad8c1a8cc0bbf661326da00dcb5a62b5bfc3
