### ISSUE TITLE
Error: fork/exec /var/task/bootstrap: permission denied

### ISSUE THREAD

**Issue by tai-acall** [aws-samples/aws-lambda-layer-awscli#38]
Hello,
thanks for this great work, this Repo. saved my day.

I just work through[ aws-version example](https://github.com/aws-samples/aws-lambda-layer-awscli/tree/master/samples/aws-version) and deploy CDK stack from AWS Cloud9, everything works.

then I tried to do the cdk synth and deploy from GitHub Actions, deploy process was done successfully but I got Lambda Runtime Error while I press the test button in the AWS Console.

> {
  "errorMessage": Error: fork/exec /var/task/bootstrap: permission denied",
  "errorType": "Runtime.InvalidEntrypoint"
}

The following step I tried but no help.
1. chmod +x for main.sh bootstrap then push to GitHub
2. run chmod +x in GitHub Actions then run cdk synth and deploy

run ls -al in GitHub Actions and confirm the permission should be fine, but still got runtime error in Lambda.

> ls -al ./src/stacks/lambda/handler/awscliFunc.d/
total 16
drwxr-xr-x 2 runner docker 4096 Apr  6 03:21 .
drwxr-xr-x 3 runner docker 4096 Apr  6 03:21 ..
-rwxrwxr-x 1 runner docker 1046 Apr  6 03:21 bootstrap
-rwxrwxr-x 1 runner docker   66 Apr  6 03:21 main.sh

Any suggestion will be helpful.

**Comment by pahud** [comment]
Thank you for your detailed feedback. Unfortunately I have no clue about this atm. However, we are planning to refactor this repo(see https://github.com/aws-samples/aws-lambda-layer-awscli/issues/39 ) in the next few days. Hopefully this will help standarize everything as we will be aligned with the official AWS CDK construct library. Let me know if you have any feedbacks. Thanks.

**Comment by tai-acall** [comment]
@pahud 
Thanks for reply.

I saw the issue https://github.com/aws-samples/aws-lambda-layer-awscli/issues/39, it's really exciting if we can just grab a CDK module (with TypeScript, off course) and done everything else in the CDK stacks.

I will close this issue and waiting for https://github.com/aws-samples/aws-lambda-layer-awscli/issues/39 updates.
