### ISSUE TITLE
refactor this repo with @aws-cdk/lambda-layer-awscli

### ISSUE THREAD

**Issue by pahud** [aws-samples/aws-lambda-layer-awscli#39]
# Background

This repository was initially created when AWS Lambda layer was announced in 2018, during which time AWS CDK was not available and we had to build everything from scratch to create our own lambda layer with AWS CLI.

As AWS CDK now comes with [@aws-cdk/lambda-layer-awscli ](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/lambda-layer-awscli), I am not planning to maintain this layer, instead, I am planning to refactor this repo to align with AWS CDK [@aws-cdk/lambda-layer-awscli ](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/lambda-layer-awscli) construct library instead.

# What will change 

1. Instead of sharing how to build the layer from scratch, we are planning to provide a sample CDK script which leverages the upstream [@aws-cdk/lambda-layer-awscli ](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/lambda-layer-awscli) to deploy your own awscli lambda layer in your own account. And you will be able to customize it in the Dockerfile provided. This means you can determine which will be bundled into this layer by customizing the Dockerfile.

2. The SAR for **aws-lambda-layer-awscli** will not update anymore and will be removed from the README. You are encouraged to build and deploy your own layer with AWS CDK.

If you are interested in the difference between this layer and [@aws-cdk/lambda-layer-awscli ](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/lambda-layer-awscli), check this issue comment for more details:
https://github.com/aws/aws-cdk/issues/13979#issuecomment-814044613

Any feedbacks are appreciated.

**Comment by tai-acall** [comment]
@pahud 

It really helpful if we can just grab a CDK module and done everything else in the CDK stacks.
I can not wait for this update.
