### ISSUE TITLE
Unable to get the awscli call to run, it always errors out

### ISSUE THREAD

**Issue by monemihir** [aws-samples/aws-lambda-layer-awscli#4]
I am running the following command:

`
/opt/awscli/aws --version
`

expecting following output
`
aws-cli/1.16.213 Python/2.7.15+ Linux/4.15.0-1043-aws botocore/1.12.203
`

but getting this error instead
```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
```

**Comment by pahud** [comment]
looking into it

**Comment by pahud** [comment]
please try this sample for `aws --version`

https://github.com/aws-samples/aws-lambda-layer-awscli/tree/master/samples/aws-version

it should work!

<img width="1217" alt="圖片" src="https://user-images.githubusercontent.com/278432/62674880-fa00b100-b9d6-11e9-9328-e992ce8a9659.png">

**Comment by pahud** [comment]
You may also deploy it with AWS CDK. Check this sample
https://github.com/aws-samples/aws-lambda-layer-awscli/tree/master/samples/aws-version
