### ISSUE TITLE
AwsCliLayer has no compatible runtimes defined

### ISSUE THREAD

**Issue by tlrdstd** [aws-samples/aws-lambda-layer-awscli#95]
When I create this layer per the README, the generated layer does not have any compatible runtimes, which means I cannot add it to any of my Lambda functions.

Looks like the runtimes need to be specified here: https://github.com/aws-samples/aws-lambda-layer-awscli/blob/main/src/custom-layer/custom-layer.ts#L12-L18

I'm attempting to work around this locally like the below, but it's not working yet. Will update if I get a good workaround.

```
import { App, CfnOutput, Construct, Stack, StackProps } from '@aws-cdk/core';
import * as lambdaLayerAwscli from '@aws-cdk/lambda-layer-awscli';

// https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#mapping-modifiers
// we want to strip the readonly property from lambdaLayerAwscli.AwsCliLayer.compatibleRuntimes,
// and this is a clean way to do it.
type CreateMutable<Type> = {
  -readonly [Property in keyof Type]: Type[Property];
};

type AwsCliLayerWithRuntimes = CreateMutable<lambdaLayerAwscli.AwsCliLayer>

export class MyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);

    const awscliLayer: AwsCliLayerWithRuntimes = new lambdaLayerAwscli.AwsCliLayer(this, 'AwsCliLayer');
    awscliLayer.compatibleRuntimes = [
      lambda.Runtime.PROVIDED_AL2,
    ]
    new CfnOutput(this, 'LayerVersionArn', { value: awscliLayer.layerVersionArn })
  }
}
```

**Comment by nascar-anna** [comment]
@tlrdstd Hi, did you figure out how to add compatibleRuntimes in the end? I am facing the same issue. Thanks!

**Comment by tlrdstd** [comment]
No, sorry, I did not. I moved to a different approach. AWS seems to have abandoned this entire package, and has ignored several open issues I've filed.
